theme: jekyll-theme-minimal
title: Solana Bench
description: Benchmarking AI's Understanding of Blockchain
show_downloads: false
google_analytics:
github_url: https://github.com/your-username/solana-gym