name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-python:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Set up Python
      run: uv python install 3.12
      
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -r requirements.txt
        
    - name: Run Python tests
      run: |
        # Run all tests except known slow ones
        # NOTE: Excluding test_e2e_jupiter_swap_simple.py as it may take >2m
        PYTHONPATH=. uv run python -m unittest discover tests/python -v -k "not test_e2e"
      timeout-minutes: 5

  test-typescript:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install TypeScript dependencies
      run: |
        cd skill_runner
        bun install
        
    - name: Run TypeScript tests
      run: |
        cd skill_runner
        bun test
      timeout-minutes: 5
      
    - name: Run ESLint
      run: |
        cd skill_runner
        bunx eslint . --max-warnings 0
      continue-on-error: true  # Don't fail CI if linting has warnings for now

  test-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [test-python, test-typescript]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install all dependencies
      run: |
        uv venv
        uv pip install -r requirements.txt
        cd skill_runner && bun install
        
    - name: Run dummy episode test
      run: |
        # This should verify that a dummy episode achieves reward > 0
        # For now, just run the voyager env test as a smoke test
        PYTHONPATH=. uv run python -m unittest tests.python.test_voyager_env -v
      timeout-minutes: 5